### ISSUE TITLE
cxy_geocode function no longer returning county names when output field specified as "full"

### ISSUE THREAD

**Issue by zmoore152** [slu-openGIS/censusxy#28]
**Describe the bug**
I've been using the cxy_geocode function for ~4 months and have just encountered a bug that I haven't run into before. When entering in a given address (including state, zip, city, etc.), the function is still returning the coordinates of matches, but has stopped returning the counties and census tracts of those matches. This is a recent phenomenon as the function was previously returning counties when the output field was specified as "full".

**Expected behavior**
Previously the cxy_geocode function would return the coordinates and county names of given addresses it was able to match, now it only returns coordinates of matches and returns "null" for county name (as well as census tract).

**To Reproduce**
library(censusxy)
sample_df = data.frame(street_name = "241 Cary Ave", state_name = "IL", zip_code = 60035, city_name = "Highland Park")
output <- cxy_geocode(sample_df, street="street_name", state = "state_name", zip="zip_code", city = "city_name", return = "geographies", benchmark = "Public_AR_Census2020", vintage = "910", output = "full")

**Desktop (please complete the following information):**
 - OS: Windows 10
 - R Version 3.6.1

**Comment by chris-prener** [comment]
hi @zmoore152 - thanks for the bug report! This is probably a change in their API - we'll look into it.

**Comment by bransonf** [comment]
@zmoore152 Thanks for providing a reproducible example, extremely helpful.

As you are probably aware, the Census Bureau is updating everything with the completion of the 2020 census, including their geocoding API. Because of this, I expect the benchmarks and vintages may be unstable. I assume `vintage = "910"` worked yesterday, but it no longer appears valid:

```
> cxy_benchmarks()
     id        benchmarkName                          benchmarkDescription isDefault
2     4    Public_AR_Current     Public Address Ranges - Current Benchmark     FALSE
21    8    Public_AR_TAB2020     Public Address Ranges - TAB2020 Benchmark     FALSE
3     9 Public_AR_Census2010 Public Address Ranges - Census 2010 Benchmark     FALSE
4  2020 Public_AR_Census2020 Public Address Ranges - Census 2020 Benchmark     FALSE

> cxy_vintages('Public_AR_Census2020')
     id           vintageName                          vintageDescription isDefault
2  2020 Census2020_Census2020 Census 2020 Vintage - Census 2020 Benchmark      TRUE
21 2010 Census2010_Census2020 Census 2010 Vintage - Census 2020 Benchmark     FALSE
```
Running your example with the vintage changed seems to work and append GEOIDs.
```
> output <- cxy_geocode(sample_df, street="street_name", state = "state_name", zip="zip_code", city = "city_name",
 return = "geographies", benchmark = "Public_AR_Census2020", vintage = "Census2020_Census2020", output = "full")
> output
   street_name state_name zip_code     city_name                            cxy_address cxy_status cxy_quality
1 241 Cary Ave         IL    60035 Highland Park 241 Cary Ave, Highland Park, IL, 60035      Match       Exact
                     cxy_matched_address cxy_tiger_line_id cxy_tiger_side   cxy_lon  cxy_lat cxy_state_id cxy_county_id
1 241 CARY AVE, HIGHLAND PARK, IL, 60035         119652033              R -87.77744 42.16783           17            97
  cxy_tract_id cxy_block_id
1       865600         2011
```

I'd advise caution using the 2020 benchmarks at the moment, and keep in mind that the geographies are changing (https://www.census.gov/geographies/mapping-files/time-series/geo/tiger-line-file.html) and won't be fully available until end of Feburary. I don't know precisely how this affects GEOIDs, but definitely worth considering.

@chris-prener We may need to change the default behavior for benchmark/vintages, but probably shouldn't do so without waiting for 2020 data to be widely adopted.

**Comment by zmoore152** [comment]
Thanks for the help everyone! I figured it might have something to do with the 2020 census, but wasn't sure.

**Comment by chris-prener** [comment]
Thanks for the detailed response @bransonf - I like the idea of waiting a bit to see how this works out. Let's leave this open as a reminder, but I'll change the tag from `bug`
