### ISSUE TITLE
CRAN issue

### ISSUE THREAD

**Issue by chris-prener** [slu-openGIS/censusxy#30]
> Please correct before 2021-02-15 to safely retain your package on CRAN.
> 
> It seems we need to remind you of the CRAN policy:
> 
> 'Packages which use Internet resources should fail gracefully with an informative message
> if the resource is not available or has changed (and not give a check warning nor error).'

**Comment by bransonf** [comment]
@chris-prener That's a bit cryptic...

Immediate thought is that we set a lengthy timeout in order for our CI to pass. `check warning` implies (I think) that this is a matter of R CMD Check on CRAN.

If it's just a network access thing, maybe we just need to add:
```
skip_on_cran()
skip_if_offline(host = "r-project.org")
```
 to: https://github.com/slu-openGIS/censusxy/blob/master/tests/testthat/test_options.R

Other thoughts?

**Comment by chris-prener** [comment]
I think we'll get dinged if we resubmit with that. What they want is an error message if the service itself is offline or unavailable. Honestly, this affects a number of `R` packages we've worked on (`gateway` and `compstatr` in particular). I haven't given it much thought, but I suspect it involves wrapping the actual requests in a `try()` ?

**Comment by bransonf** [comment]
Per https://books.ropensci.org/http-testing/graceful.html
> Do not forget CRAN’s “graceful failure” policy is mostly about ensuring a clean R CMD check result on CRAN platforms (0 ERROR, 0 WARNING, 0 NOTE) even when the web service you’re wrapping has some hiccups.

Our [CRAN check results](https://cran.r-project.org/web/checks/check_results_censusxy.html) only fail due to [testing benchmarks/vintages](https://github.com/slu-openGIS/censusxy/blob/master/tests/testthat/test_options.R) and the fact that the vintage we are using is no longer valid. `Public_AR_Census2010` needs a bump to `Public_AR_Census2020`

An important aside: [`eiCompare`](https://cran.r-project.org/web/packages/eiCompare/index.html) now depends on `censusxy`

Let's not overthink. I'll push a fix by tomorrow evening if you can handle the resubmit to CRAN.

**Comment by chris-prener** [comment]
If it works to get it to stay on CRAN, that is fine. We'll see what the maintainers say. Let me know when it is ready to go!
